name: momentum
description: Habits & Todos app with streaks, reminders, analytics, sync, and AI time blocking.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  uuid: ^4.5.1
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  intl: ^0.19.0
  reorderables: ^0.6.0
  flutter_slidable: ^3.1.0
  flutter_spinkit: ^5.2.1
  flutter_animate: ^4.5.0
  flutter_markdown: ^0.7.4+3
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  # UI enhancement packages for redesign
  grouped_list: ^5.1.2
  smooth_page_indicator: ^1.1.0
  # Optional sync/shared lists (Level 3)
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  # This is the package for the icon generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# This is the configuration for the icon generator
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png" # Make sure you have this folder and file
  min_sdk_android: 21